library(readxl)
data <- read_excel("C:/Users/Suryaa/OneDrive/Desktop/R filesw/data.xlsx")
m1=mean(data$min_price)
print(m1)
m2=mean(data$max_price)
print(m2)
m3=mean(data$modal_price)
print(m3)
sd1=sd(data$min_price)
print(sd1)
sd2=sd(data$max_price)
print(sd2)
sd3=sd(data$modal_price)
print(sd3)
